; ARM64 Apple Silicon Assembly
; Generated by ast_to_arm64.c
;
.section __TEXT,__cstring,cstring_literals
_str0:
	.asciz "tie!"
_str1:
	.asciz "computer:"
_str2:
	.asciz "player:"
_str3:
	.asciz "comp"
_str4:
	.asciz "player"

.section __DATA,__bss
_rt_buf:
	.space 33

.comm _gv_comp, 8, 3
.comm _gv_player, 8, 3
.comm _gv_win, 8, 3

.section __TEXT,__text
.globl _main

; ── runtime helper: int64 → decimal string ──────────────
; Input:  x0 = int64 value
; Output: x0 = pointer to null-terminated string in _rt_buf
; Clobbers: x1-x7
_int64_to_str:
	stp  x29, x30, [sp, #-16]!
	mov  x29, sp
	adrp x1, _rt_buf@PAGE
	add  x1, x1, _rt_buf@PAGEOFF   ; x1 = buf base

	; handle zero
	cbnz x0, _i2s_nonzero
	mov  w2, #48
	strb w2, [x1]
	mov  w2, #10
	strb w2, [x1, #1]              ; newline
	mov  w2, #0
	strb w2, [x1, #2]              ; null terminator
	mov  x0, x1
	ldp  x29, x30, [sp], #16
	ret

_i2s_nonzero:
	mov  x6, #0                    ; x6 = negative flag
	tbz  x0, #63, _i2s_positive
	mov  x6, #1
	neg  x0, x0
_i2s_positive:
	add  x3, x1, #30              ; x3 = write pointer (end)
	strb w4, [x1, #1]             ; newline at buf+31
	mov  w4, #0
	strb w4, [x3, #2]             ; null terminator at buf+32

_i2s_digit_loop:
	cbz  x0, _i2s_done_digits
	mov  x5, #10
	udiv x7, x0, x5               ; x7 = x0 / 10
	msub x4, x7, x5, x0           ; x4 = x0          
	add  w4, w4, #48              ; to ASCII
	strb w4, [x3]
	sub  x3, x3, #1
	mov  x0, x7
	b    _i2s_digit_loop

_i2s_done_digits:
	cbz  x6, _i2s_no_neg
	mov  w4, #45                  ; '-'
	strb w4, [x3]
	sub  x3, x3, #1
_i2s_no_neg:
	add  x0, x3, #1               ; x0 = pointer to first digit
	ldp  x29, x30, [sp], #16
	ret

_main:
	stp  x29, x30, [sp, #-16]!
	mov  x29, sp
	mov  x8, #1
	mov  x10, x8
	mov  x8, #3
	sub  x8, x8, x10
	add  x8, x8, #1
	mov  x0, x8
	str  x10, [sp, #-16]!
	bl   _arc4random_uniform
	ldr  x10, [sp], #16
	add  x8, x0, x10
	adrp x9, _gv_comp@PAGE
	str  x8, [x9, _gv_comp@PAGEOFF]
	mov  x8, #2
	adrp x9, _gv_player@PAGE
	str  x8, [x9, _gv_player@PAGEOFF]
	adrp x9, _gv_player@PAGE
	ldr  x8, [x9, _gv_player@PAGEOFF]
	mov  x10, x8
	adrp x9, _gv_comp@PAGE
	ldr  x8, [x9, _gv_comp@PAGEOFF]
	cmp  x10, x8
	cset x8, eq
	cbz  x8, _Ifalse0
	adrp x0, _str0@PAGE
	add  x0, x0, _str0@PAGEOFF
	bl   _puts
	adrp x0, _str1@PAGE
	add  x0, x0, _str1@PAGEOFF
	bl   _puts
	adrp x9, _gv_comp@PAGE
	ldr  x8, [x9, _gv_comp@PAGEOFF]
	mov  x0, x8
	bl   _int64_to_str
	bl   _puts
	adrp x0, _str2@PAGE
	add  x0, x0, _str2@PAGEOFF
	bl   _puts
	adrp x9, _gv_player@PAGE
	ldr  x8, [x9, _gv_player@PAGEOFF]
	mov  x0, x8
	bl   _int64_to_str
	bl   _puts
_Ifalse0:
	adrp x9, _gv_player@PAGE
	ldr  x8, [x9, _gv_player@PAGEOFF]
	mov  x10, x8
	mov  x8, #1
	cmp  x10, x8
	cset x8, eq
	cbz  x8, _Ifalse1
	adrp x9, _gv_comp@PAGE
	ldr  x8, [x9, _gv_comp@PAGEOFF]
	mov  x10, x8
	mov  x8, #2
	cmp  x10, x8
	cset x8, eq
	cbz  x8, _Ifalse2
	adrp x8, _str3@PAGE
	add  x8, x8, _str3@PAGEOFF
	adrp x9, _gv_win@PAGE
	str  x8, [x9, _gv_win@PAGEOFF]
	b    _Iend2
_Ifalse2:
	adrp x8, _str4@PAGE
	add  x8, x8, _str4@PAGEOFF
	adrp x9, _gv_win@PAGE
	str  x8, [x9, _gv_win@PAGEOFF]
_Iend2:
_Ifalse1:
	adrp x9, _gv_player@PAGE
	ldr  x8, [x9, _gv_player@PAGEOFF]
	mov  x10, x8
	mov  x8, #2
	cmp  x10, x8
	cset x8, eq
	cbz  x8, _Ifalse3
	adrp x9, _gv_comp@PAGE
	ldr  x8, [x9, _gv_comp@PAGEOFF]
	mov  x10, x8
	mov  x8, #3
	cmp  x10, x8
	cset x8, eq
	cbz  x8, _Ifalse4
	adrp x8, _str3@PAGE
	add  x8, x8, _str3@PAGEOFF
	adrp x9, _gv_win@PAGE
	str  x8, [x9, _gv_win@PAGEOFF]
	b    _Iend4
_Ifalse4:
	adrp x8, _str4@PAGE
	add  x8, x8, _str4@PAGEOFF
	adrp x9, _gv_win@PAGE
	str  x8, [x9, _gv_win@PAGEOFF]
_Iend4:
_Ifalse3:
	adrp x9, _gv_player@PAGE
	ldr  x8, [x9, _gv_player@PAGEOFF]
	mov  x10, x8
	mov  x8, #3
	cmp  x10, x8
	cset x8, eq
	cbz  x8, _Ifalse5
	adrp x9, _gv_comp@PAGE
	ldr  x8, [x9, _gv_comp@PAGEOFF]
	mov  x10, x8
	mov  x8, #1
	cmp  x10, x8
	cset x8, eq
	cbz  x8, _Ifalse6
	adrp x8, _str3@PAGE
	add  x8, x8, _str3@PAGEOFF
	adrp x9, _gv_win@PAGE
	str  x8, [x9, _gv_win@PAGEOFF]
	b    _Iend6
_Ifalse6:
	adrp x8, _str4@PAGE
	add  x8, x8, _str4@PAGEOFF
	adrp x9, _gv_win@PAGE
	str  x8, [x9, _gv_win@PAGEOFF]
_Iend6:
_Ifalse5:
	adrp x9, _gv_win@PAGE
	ldr  x8, [x9, _gv_win@PAGEOFF]
	mov  x0, x8
	bl   _puts
	mov  x0, #0
	ldp  x29, x30, [sp], #16
	ret

